list_a_94a = [ 
            "Be around lots of people"
            ,"Social interactions"
            ,"Making new friends"
            ,"Talking more"
            ,"Excitement and activity"
            ,"Going out"
            ,"Multitasking in a busy environment"
            ,"Start conversations"
            ,"Thrive in social settings"
            ,"Big party"
            ,"Easy to approach new people"
            ,"Expressing thoughts out loud"
            ,"Brainstorming with others"
            ,"Face-to-face"
            ,"Noisy environment"
            ,"Present moment"
            ,"Concrete facts"
            ,"Practical applications"
            ,"Hands-on experience"
            ,"Details"
            ,"Focus on facts"
            ,"Tangible and proven"
            ,"What’s real"
            ,"Routine"
            ,"Practical"
            ,"Details"
            ,"How things work"
            ,"Rarely"
            ,"Past experiences"
            ,"Concrete facts"
            ,"Sensory activities"
            ,"Step-by-step"
            ,"Current realities"
            ,"Faces"
            ,"Practical details"
            ,"Tried-and-true"
            ,"Logic"
            ,"Fairness"
            ,"Competence"
            ,"Objectivity "
            ,"Facts"
            ,"Tough feedback"
            ,"Consequences"
            ,"Stay calm"
            ,"Focusing on tasks"
            ,"Efficiency"
            ,"Pros and cons"
            ,"Achievements"
            ,"Being right"
            ,"Analyze and offer solutions"
            ,"Direct, honest feedback"
            ,"Objective"
            ,"Principles"
            ,"Completing tasks"
            ,"Solve it immediately"
            ,"Stating facts"
            ,"Logic"
            ,"Detailed plan"
            ,"Structure"
            ,"Knowing what to expect"
            ,"Plan things out"
            ,"Stick to a schedule"
            ,"Finishing ahead"
            ,"Organized"
            ,"Strict itinerary"
            ,"Checking items off"
            ,"Make decisions quickly"
            ,"Stick to a plan"
            ,"Resolve quickly"
            ,"Clear goals"
            ,"Work steadily in advance"
            ,"Stressed when undecided"
            ,"Complete early"
            ,"Plan every step"
            ,"Certainty and predictability"
            ,"Plan in detail"
            ,"Setting in stone"
            ,"Routines and schedules"
            ,"Resolved"
            ,"Clear idea"
            ,"Stick to a plan"
            ,"Completing tasks"
            ,"Structure"
            ,"Planned out"
            ,"One task at a time"
            ,"Make decisions early"
            ,"Comfort in closure"
            ,"Resolve it quickly"
            ,"Stick to rules"
            ,"Controlled environment"
            ,"Clear direction"
            ,"Sticking to plans"
            ,"Knowing what the day will look like"
            ,"Finalized"
]

list_a_94b = [
            "Spend time alone"
            ,"Quiet reflection"
            ,"Close circle of friends"
            ,"Listening more"
            ,"Calm and peaceful environment"
            ,"Staying home"
            ,"One task at a time in a quiet space"
            ,"Wait for others"
            ,"Get tired"
            ,"Quiet evening with one or two friends"
            ,"Not as easy"
            ,"Keeping them to yourself"
            ,"Working alone"
            ,"Communicate in writing"
            ,"Quiet space"
            ,"Future possibilities"
            ,"Abstract ideas"
            ,"Creative possibilities"
            ,"Exploring new concepts"
            ,"Big picture"
            ,"Focus on theory"
            ,"Instincts"
            ,"Underlying meanings"
            ,"Explore new ways"
            ,"Big ideas"
            ,"Imaginative"
            ,"Why things happen"
            ,"Frequently"
            ,"Future scenarios"
            ,"Metaphors and analogies"
            ,"Mental exercises"
            ,"Different approaches"
            ,"Future potential"
            ,"Ideas"
            ,"Experience itself"
            ,"New ideas"
            ,"Emotions"
            ,"Compassion"
            ,"Empathy"
            ,"Emotional understanding"
            ,"Feelings"
            ,"Gentle encouragement"
            ,"Emotional impact"
            ,"Empathize"
            ,"Maintaining harmony"
            ,"Emotional support"
            ,"How others feel"
            ,"Helping others"
            ,"Being kind"
            ,"Listen and offer support"
            ,"Considerate of feelings"
            ,"Compassionate"
            ,"Personal values"
            ,"Supporting emotionally"
            ,"Understand emotions"
            ,"Sharing feelings"
            ,"Personal experiences"
            ,"Go with the flow"
            ,"Flexibility"
            ,"Being surprised"
            ,"Be spontaneous"
            ,"Leave room for flexibility"
            ,"Working up until the deadline"
            ,"Open-ended"
            ,"Deciding as you go"
            ,"Freedom to improvise"
            ,"Wait for more information"
            ,"Adjust as things develop"
            ,"Explore possibilities"
            ,"Different paths"
            ,"Wait until the last minute"
            ,"Enjoy keeping options open"
            ,"Take time"
            ,"Dive in and adjust"
            ,"Spontaneity and flexibility"
            ,"Keep options open"
            ,"Keeping things flexible"
            ,"Mixing things up"
            ,"Leaving room for changes"
            ,"Space for spontaneity"
            ,"Adapt to changes"
            ,"Exploring new ideas"
            ,"Flexibility"
            ,"Flexible"
            ,"Juggling multiple tasks"
            ,"Wait for more information"
            ,"Enjoy keeping things open-ended"
            ,"Explore options"
            ,"New ways"
            ,"Adaptable situations"
            ,"Explore different paths"
            ,"Adjusting them"
            ,"Unexpected opportunities"
            ,"Keeping them flexible"
]

# ------------------------------




list_ap_94a = [
            "بودن با افراد زیاد"
            ,"تعاملات اجتماعی"
            ,"دوستان جدید"
            ,"بیشتر صحبت می‌کنید"
            ,"هیجان و فعالیت"
            ,"بیرون رفتن"
            ,"انجام چند کار همزمان"
            ,"شروع مکالمه"
            ,"خیر مخالفم"
            ,"مهمانی بزرگ"
            ,"راحتی در آشنا شدن با افراد جدید"
            ,"بیان افکار با صدای بلند"
            ,"بحث با دیگران"
            ,"رودررو"
            ,"محیط شلوغ"
            ,"به دیگران می‌گویید"
            ,"اعتماد به دیگران"
            ,"کمک از دیگران"
            ,"ادامه کار"
            ,"محیط‌های اجتماعی"
            ,"موافقم"
            ,"کنار دیگران"
            ,"پیوستن به گروه"
            ,"خوشحال می‌شوید"
            ,"محیط‌های اجتماعی"
            ,"مخالفم"
            ,"بله درست است"
            ,"شلوغ و پر سر و صدا"
            ,"ارتباط با دیگران"
            ,"به سرعت ارتباط برقرار می‌کنید"
            ,"تقسیم وظایف"
            ,"لحظه حال"
            ,"تجربیات گذشته"
            ,"حقایق واقعی"
            ,"کاربردهای عملی"
            ,"سخت"
            ,"جزئیات"
            ,"تمرکز بر حقایق"
            ,"کاملا موافقم"
            ,"روال معمول"
            ,"جزئیات"
            ,"چگونه کار می‌کنند"
            ,"به ندرت"
            ,"حل مسائل کوتاه‌مدت"
            ,"بله اکثرا"
            ,"بررسی اطلاعات واقعی"
            ,"جزئیات"
            ,"کارهایی که مسیر مشخص دارند"
            ,"تجربیات عملی"
            ,"منطق و واقعیت‌ها"
            ,"چگونگی اجرا"
            ,"تجربیات گذشته"
            ,"زمان حال"
            ,"مراحل ازپیش تایین شده"
            ,"واقع بین"
            ,"راه‌حل‌های سریع و عملی"
            ,"نه خیلی"
            ,"آنچه که می‌توانید ببینید"
            ,"منطق"
            ,"استدلال های مبتنی بر حقیقت"
            ,"توانمندی ها"
            ,"اصول کلی"
            ,"اثبات حرف های خود"
            ,"استدلال ها"
            ,"دنبال حقیقت"
            ,"عدالت"
            ,"محیط رقابتی"
            ,"کارایی و سودمندی"
            ,"خیر"
            ,"حل مسائل پیچیده"
            ,"موافقم"
            ,"فکت‌ها و اطلاعات علمی"
            ,"تأثیرگذاری و نتیجه عملی"
            ,"درست است"
            ,"کارایی"
            ,"خیر اینطور فکر نمیکنم"
            ,"رسیدن به اهداف خود"
            ,"برنامه دقیق"
            ,"ساختار و نظم"
            ,"بله دوست دارم"
            ,"بله دوست دارم"
            ,"خیر برایم چالش ندارد"
            ,"پایبندی به برنامه‌ها"
            ,"خیر فقط گاهی"
            ,"موافقم"
            ,"محیط‌های ساختاریافته"
            ,"بله درست است"
            ,"برنامه ریزی کردن"
            ,"راه‌حل عملی"
            ,"چارچوب‌های شناخته شده"
            ,"برنامه میریزم"
            ,"نقش‌های فردی و مسئولیت‌های مشخص"
            ,"تلاش‌های سازماندهی شده و مداوم"
            ,"موافقم"
]




list_ap_94b = [
            "گذراندن زمان به تنهایی"
            ,"تفکر و تأمل"
            ,"دایره‌ای از دوستان نزدیک"
            ,"بیشتر گوش می‌دهید"
            ,"محیط آرام و ساکت"
            ,"ماندن در خانه"
            ,"یک کار در فضای آرام"
            ,"منتظر دیگران"
            ,"اینطور فکر میکنم"
            ,"شب آرام با یک یا دو دوست"
            ,"چندان راحت نیست"
            ,"نگه داشتن افکار برای خودتان"
            ,"کار به تنهایی"
            ,"از طریق نوشتار"
            ,"فضای ساکت و تنها"
            ,"خودتان انجام می‌دهید"
            ,"استقلال"
            ,"راه‌حل‌های شخصی"
            ,"استراحت و آرامش"
            ,"محیط‌های آرام و فردی"
            ,"مخالفم"
            ,"تنها"
            ,"فعالیت به تنهایی"
            ,"ترجیح می‌دهید تصمیم بگیرید"
            ,"محیط‌های آرام و فردی"
            ,"موافقم"
            ,"خیر اینطور نیست"
            ,"آرام و منظم"
            ,"کار به تنهایی"
            ,"وقت زیادی نیاز دارید"
            ,"انجام به تنهایی"
            ,"امکانات آینده"
            ,"ایده‌های خلاقانه"
            ,"ایده‌های انتزاعی"
            ,"امکانات خلاقانه"
            ,"آسان"
            ,"تصویر کلی"
            ,"تمرکز بر نظریه‌ها"
            ,"خیر اینطور نیست"
            ,"کشف روش‌های جدید"
            ,"ایده‌های بزرگ"
            ,"چرا اتفاق می‌افتند"
            ,"مرتباً"
            ,"برنامه‌های بلندمدت"
            ,"خیر برخی اوقات"
            ,"اعتماد به الهام"
            ,"کلیات"
            ,"خلاقیت و نوآوری"
            ,"نظریه‌ها و مفاهیم"
            ,"معانی عمیق و انتزاعی"
            ,"نتایج"
            ,"ایده‌های جدید"
            ,"آینده و امکانات جدید"
            ,"راه حل های خلاقانه"
            ,"رویاپرداز"
            ,"راه‌حل‌های خلاقانه"
            ,"زیاد"
            ,"آنچه که می‌توانید تصور کنید"
            ,"احساسات"
            ,"آنچه که از نظر عاطفی برایم قابل درک است"
            ,"احساسات و رفتار"
            ,"احساسات"
            ,"محافظت از احساسات دیگران"
            ,"حس شخصی تان"
            ,"توجه به تأثیر عاطفی"
            ,"همدردی"
            ,"محیط همکاری و همدلی"
            ,"احساسات افراد"
            ,"بله"
            ,"برقراری ارتباط عمیق"
            ,"مخالفم"
            ,"احساسات و تجربیات شخصی"
            ,"کیفیت و ارزش‌های فردی"
            ,"خیر اینطور نیست"
            ,"تاثیر جنبه های عاطفی"
            ,"بله اینطور است"
            ,"کمک به دیگران"
            ,"به جریان امور سپردن"
            ,"انعطاف‌پذیری"
            ,"خیر دوست ندارم"
            ,"خیلی علاقه و حوصله اش را ندارم"
            ,"بله اکثرا برایم چالش دارد"
            ,"پاسخ به تغییرات"
            ,"بله اکثرا"
            ,"مخالفم"
            ,"محیط‌های غیر رسمی و آزاد"
            ,"خبر برنامه منعطفی دارم"
            ,"بداهه پردازی"
            ,"بررسی ابعاد مختلف مشکل"
            ,"سازگاری با تغییرات"
            ,"با جریان روز پیش می روم "
            ,"همکاری آزاد و انعطاف‌پذیر"
            ,"انفجارهای خودبخودی انرژی"
            ,"مخالفم"
]
