list_q_94 = [
            "Do you prefer to be around lots of people or spend time alone?"
            ,"Do you feel more energized by social interactions or quiet reflection?"
            ,"Are you more comfortable making new friends or spending time with a close circle of friends?"
            ,"Do you find yourself talking more than listening in conversations?"
            ,"Do you seek excitement and activity, or do you prefer a calm and peaceful environment?"
            ,"When you have free time, do you prefer going out or staying home?"
            ,"Do you enjoy multitasking in a busy environment or working on one task at a time in a quiet space?"
            ,"Do you usually start conversations or wait for others to initiate?"
            ,"Do you get tired after being in a crowd for a long time, or do you thrive in social settings?"
            ,"Would you rather go to a big party or have a quiet evening with one or two friends?"
            ,"Do you find it easy to approach new people and make friends?"
            ,"Are you more comfortable expressing your thoughts out loud or keeping them to yourself?"
            ,"When working on a project, do you enjoy brainstorming with others or working alone?"
            ,"Do you feel more connected to people when you’re talking face-to-face or when you communicate in writing?"
            ,"Do you feel more productive in a noisy environment or in a quiet, solitary space?"
            ,"Do you focus more on the present moment or future possibilities?"
            ,"Do you prefer concrete facts or abstract ideas?"
            ,"Are you more interested in practical applications or creative possibilities?"
            ,"When learning something new, do you prefer hands-on experience or exploring new concepts?"
            ,"Do you pay more attention to details or the overall big picture?"
            ,"When solving a problem, do you focus on the facts or the underlying theory?"
            ,"Do you trust information that is tangible and proven, or do you trust your instincts more?"
            ,"Do you tend to focus on what’s real and happening now, or do you look for underlying meanings and possibilities?"
            ,"Do you prefer to follow a routine or explore new ways of doing things?"
            ,"Do you prefer practical or imaginative solutions?"
            ,"Do you remember details about your daily life or big ideas that inspire you?"
            ,"Are you more interested in how things work or why things happen?"
            ,"Do you notice patterns and connections between seemingly unrelated things?"
            ,"Do you enjoy learning from past experiences or imagining future scenarios?"
            ,"Do you focus on concrete facts when explaining something or use metaphors and analogies?"
            ,"Do you enjoy activities that engage your senses (e.g., cooking, gardening) or mental exercises (e.g., brainstorming)?"
            ,"Do you prefer learning step-by-step or exploring different approaches and ideas?"
            ,"Are you more focused on current realities or envisioning future potential?"
            ,"Do you tend to remember faces or ideas better?"
            ,"When planning a trip, do you focus more on practical details or the experience itself?"
            ,"Do you prefer following tried-and-true methods or experimenting with new ideas?"
            ,"Do you make decisions based on logic or emotions?"
            ,"Do you prioritize fairness or compassion in decision-making?"
            ,"Do you value competence or empathy more in others?"
            ,"When resolving conflicts, do you aim for objectivity or emotional understanding?"
            ,"Do you prefer to resolve issues based on the facts or the feelings involved?"
            ,"Do you appreciate tough feedback that helps you improve or gentle encouragement?"
            ,"When making decisions, do you consider the consequences first or how it will affect people emotionally?"
            ,"Do you find it easier to stay calm in difficult situations or do you empathize with others' emotions?"
            ,"When working in a group, do you prefer focusing on tasks or maintaining harmony?"
            ,"Do you value efficiency more than emotional support?"
            ,"When faced with a difficult decision, do you think through all the pros and cons or consider how others might feel about it?"
            ,"Are you more motivated by achievements or helping others?"
            ,"Do you prioritize being right or being kind?"
            ,"In conversations, do you tend to analyze and offer solutions or listen and offer support?"
            ,"Do you prefer to give direct, honest feedback or be considerate of others’ feelings?"
            ,"Do you believe that being objective is more important than being compassionate?"
            ,"Do you prefer making decisions based on principles or personal values?"
            ,"Are you more focused on completing tasks or supporting others emotionally?"
            ,"When you see a problem, do you want to solve it immediately or understand how it makes others feel?"
            ,"Do you approach difficult conversations by stating the facts or sharing your feelings?"
            ,"Do you prefer debates based on logic or personal experiences?"
            ,"Do you prefer to have a detailed plan or go with the flow?"
            ,"Are you more comfortable with structure or flexibility?"
            ,"Do you prefer knowing what to expect or being surprised?"
            ,"Do you like to plan things out or be spontaneous?"
            ,"Do you prefer to stick to a schedule or leave room for flexibility?"
            ,"Do you like finishing tasks ahead of time or working up until the deadline?"
            ,"Do you feel more comfortable when things are organized or when things are open-ended?"
            ,"When traveling, do you prefer having a strict itinerary or deciding as you go?"
            ,"Do you enjoy checking items off a to-do list or having the freedom to improvise?"
            ,"Do you prefer making decisions quickly or waiting until you have all the information?"
            ,"Do you prefer sticking to a plan or adjusting as things develop?"
            ,"Do you like resolving issues quickly or exploring different possibilities before deciding?"
            ,"Do you enjoy having clear goals or exploring different paths to the outcome?"
            ,"When faced with a deadline, do you work steadily in advance or wait until the last minute?"
            ,"Do you feel stressed when things are left undecided, or do you enjoy keeping options open?"
            ,"Do you prefer to complete tasks early or take your time to perfect them?"
            ,"When starting a project, do you plan every step or dive right in and adjust as you go?"
            ,"Do you prefer certainty and predictability or spontaneity and flexibility?"
            ,"Do you prefer to plan in detail or keep your options open for as long as possible?"
            ,"When making plans with others, do you prefer setting things in stone or keeping things flexible?"
            ,"Do you prefer routines and schedules, or do you enjoy mixing things up?"
            ,"When making decisions, do you like having things resolved or leaving room for changes?"
            ,"Do you like to have a clear idea of what you're doing each day or leave space for spontaneity?"
            ,"Do you find it easier to stick to a plan or adapt to changes?"
            ,"Do you get satisfaction from completing tasks or exploring new ideas?"
            ,"Are you more comfortable with structure or flexibility in your daily life?"
            ,"Do you feel more at ease when things are planned out or when you can be flexible?"
            ,"Do you prefer working on one task at a time or juggling multiple tasks?"
            ,"Do you like to make decisions early or wait until you have more information?"
            ,"Do you find comfort in having closure, or do you enjoy keeping things open-ended?"
            ,"When faced with uncertainty, do you try to resolve it quickly or explore different options?"
            ,"Do you prefer to stick to the rules or find new ways to achieve goals?"
            ,"Do you feel more comfortable in a controlled environment or in situations that allow for adaptation?"
            ,"Do you prefer having a clear direction or exploring different paths as you go?"
            ,"Do you prefer sticking to plans or adjusting them as needed?"
            ,"Do you like knowing what the day will look like or being open to unexpected opportunities?"
            ,"Do you like decisions to be finalized or enjoy keeping them flexible?"
]

# --------------------------------------

list_qp_94 = [
            "آیا ترجیح می‌دهید با افراد زیادی باشید یا زمان خود را به تنهایی بگذرانید؟"
            ,"آیا تعاملات اجتماعی به شما انرژی می‌دهد یا تفکر و تأمل؟"
            ,"آیا شما راحت‌ تر با دوستان جدید ارتباط برقرار می‌کنید یا ترجیح می‌دهید با دایره‌ای از دوستان نزدیک باشید؟"
            ,"معمولا در بحث های جمعی بیشتر صحبت می‌کنید یا گوش می‌دهید؟"
            ,"آیا به دنبال هیجان و فعالیت هستید یا محیط آرام و ساکت را ترجیح می‌دهید؟"
            ,"در زمان‌های آزاد، ترجیح می‌دهید بیرون بروید یا در خانه بمانید؟"
            ,"آیا از انجام چند کار همزمان در یک محیط شلوغ لذت می‌برید یا ترجیح می‌دهید یک کار را در یک فضای آرام انجام دهید؟"
            ,"آیا شما معمولاً شروع کننده مکالمات هستید یا منتظر می‌مانید تا دیگران شروع کنند؟"
            ,"به نظر شما فکر شبکه بندی یا تبلیغ کردن خودتان برای غریبه‌ها بسیار ترسناک یا سخت است."
            ,"آیا ترجیح می‌دهید به یک مهمانی بزرگ بروید یا یک شب آرام با یک یا دو دوست داشته باشید؟"
            ,"آیا برای شما راحت است با افراد جدید آشنا شوید و دوست شوید؟"
            ,"آیا شما بیشتر تمایل دارید که افکارتان را با صدای بلند بیان کنید یا آنها را برای خودتان نگه دارید؟"
            ,"وقتی روی یک پروژه کار می‌کنید، آیا از بحث و گفتگو با دیگران لذت می‌برید یا ترجیح می‌دهید به تنهایی کار کنید؟"
            ,"آیا در ارتباط با افراد بیشتر احساس ارتباط می‌کنید وقتی رودررو صحبت می‌کنید یا از طریق نوشتار؟"
            ,"آیا در محیط‌های شلوغ و پر سر و صدا بهتر کار می‌کنید یا در یک فضای ساکت و تنها؟"
            ,"آیا به دیگران می‌گویید چگونه باید کارها را انجام دهند یا خودتان به تنهایی انجام می‌دهید؟"
            ,"آیا در کار گروهی به راحتی به دیگران اعتماد می‌کنید یا تمایل دارید بیشتر مستقل باشید؟"
            ,"آیا در مواجهه با مشکلات بیشتر به دنبال کمک از دیگران هستید یا خودتان به دنبال راه‌حل می‌گردید؟"
            ,"آیا بعد از یک روز شلوغ به کارهای جدید ادامه می‌دهید یا به استراحت و آرامش نیاز دارید؟"
            ,"آیا احساس می‌کنید در محیط‌های اجتماعی به خوبی عمل می‌کنید یا در محیط‌های آرام و فردی بهتر عمل می‌کنید؟"
            ,"رفتن به سوی شخصی که به نظرتان جالب است و باز کردن سر صحبت با او برای تان راحت است."
            ,"بیشتر ترجیح می‌دهید کنار دیگران باشید یا تنها؟"
            ,"آیا در زمان‌های آزاد ترجیح می‌دهید به گروهی از دوستان بپیوندید یا به تنهایی فعالیت کنید؟"
            ,"آیا از اینکه دیگران از شما درخواست کمک کنند خوشحال می‌شوید یا ترجیح می‌دهید خودتان تصمیم بگیرید؟"
            ,"آیا احساس می‌کنید در محیط‌های اجتماعی به خوبی عمل می‌کنید یا در محیط‌های آرام و فردی بهتر عمل می‌کنید؟"
            ,"شما اکثرا از سرگرمی‌ها یا فعالیت‌های انفرادی بیشتر از موارد گروهی لذت می‌برید."
            ,"معمولا به آسانی می‌توانید با افرادی که تازه ملاقات کرده‌اید ارتباط برقرار کنید."
            ,"آیا در محیط‌های شلوغ و پر سر و صدا بهتر کار می‌کنید یا در محیط‌های آرام و منظم؟"
            ,"آیا در کارهای گروهی تمایل دارید با دیگران ارتباط برقرار کنید یا ترجیح می‌دهید خودتان به تنهایی کار کنید؟"
            ,"آیا در موقعیت‌های اجتماعی به سرعت با دیگران ارتباط برقرار می‌کنید یا وقت زیادی برای شناخت آنها نیاز دارید؟"
            ,"آیا در کارهای گروهی ترجیح می‌دهید وظایف را با دیگران تقسیم کنید یا خودتان به تنهایی انجام دهید؟"
            ,"آیا بیشتر به لحظه حال توجه می‌کنید یا به امکانات آینده؟"
            ,"آیا هنگام مواجهه با مشکلی جدید، بیشتر به ایده‌های خلاقانه فکر می‌کنید یا به تجربیات گذشته تکیه می‌کنید؟"
            ,"آیا ترجیح می‌دهید به حقایق واقعی توجه کنید یا به ایده‌های انتزاعی؟"
            ,"آیا بیشتر به کاربردهای عملی علاقه دارید یا به امکانات خلاقانه؟"
            ,"اینکه برای کسب درآمد زندگی تان رویاهای تخیلی تصور کنید برایتان سخت است یا آسان؟"
            ,"آیا بیشتر به جزئیات توجه می‌کنید یا به تصویر کلی؟"
            ,"در حل مشکلات آیا بیشتر بر روی حقایق تمرکز می‌کنید یا نظریه‌های زیرین؟"
            ,"شما باور دارید که فکر کردن به پرسش‌های فلسفی انتزاعی اتلاف وقت است."
            ,"آیا ترجیح می‌دهید یک روال را دنبال کنید یا روش‌های جدیدی برای انجام کارها کشف کنید؟"
            ,"آیا بیشتر جزئیات مربوط به زندگی روزمره خود را به خاطر می‌آورید یا ایده‌های بزرگ الهام‌بخش؟"
            ,"آیا بیشتر به اینکه چیزها چگونه کار می‌کنند علاقه‌مند هستید یا به اینکه چرا اتفاق می‌افتند؟"
            ,"الگو و ارتباطات بین چیزهای نامرتبط را به ندرت تشخیص میدهید یا مرتبا؟"
            ,"آیا بیشتر تمایل دارید که ایده‌ها و برنامه‌های بلندمدت داشته باشید یا به حل مسائل کوتاه‌مدت بپردازید؟"
            ,"وقتی بحث به شدت تئوری می‌شود خسته می‌شوید یا علاقه خود را از دست می‌دهید."
            ,"آیا در مواجهه با مسائل جدید، ترجیح می‌دهید ابتدا اطلاعات واقعی را بررسی کنید یا به الهام خود اعتماد کنید؟"
            ,"آیا در هنگام برنامه‌ریزی، به جزئیات توجه می‌کنید یا به کلیات؟"
            ,"آیا ترجیح می‌دهید کارهایی که مسیر مشخصی دارند را انجام دهید یا از خلاقیت و نوآوری استفاده کنید؟"
            ,"آیا برای یادگیری مطالب جدید بیشتر به تجربیات عملی اعتماد می‌کنید یا به نظریه‌ها و مفاهیم؟"
            ,"آیا بیشتر به منطق و واقعیت‌ها توجه می‌کنید یا به معانی عمیق و مفاهیم انتزاعی؟"
            ,"آیا وقتی به یک پروژه جدید فکر می‌کنید، بیشتر به چگونگی اجرای پروژه توجه می‌کنید یا به نتایج آن؟"
            ,"آیا ترجیح می‌دهید از تجربیات گذشته برای حل مسائل استفاده کنید یا به دنبال ایده‌های جدید باشید؟"
            ,"آیا از زندگی کردن در زمان حال لذت می‌برید یا به آینده و امکانات جدید فکر می‌کنید؟"
            ,"به صورت کلی، راه حل های خلاقانه را ترجیح میدهید یا استفاده از مراحل ازپیش تایین شده را؟"
            ,"آیا بیشتر خود را فردی رویاپرداز میدانید یا واقع بین؟"
            ,"آیا برای حل مسائل پیچیده به دنبال راه‌حل‌های خلاقانه می‌گردید یا راه‌حل‌های سریع و عملی؟"
            ,"چقدر تمایل به بحث در مورد این نظریه‌ها دارید که جهان در آینده چه شکلی خواهد بود؟"
            ,"آیا بیشتر به آنچه که می‌توانید ببینید اعتماد می‌کنید یا به آنچه که می‌توانید تصور کنید؟"
            ,"آیا تصمیمات خود را بیشتر بر اساس منطق می‌گیرید یا احساسات؟"
            ,"معمولاً بیشتر توسط آنچه که از نظر عاطفی برایتان قابل درک است متقاعد می‌شوید یا استدلال‌های مبتنی بر حقیقت؟"
            ,"آیا در دیگران بیشتر به توانمندی های آنها توجه میکنید یا به احساسات و رفتار آنها؟"
            ,"آیا بیشتر به اصول کلی توجه می‌کنید یا به احساسات؟"
            ,"در اختلاف‌ها، اثبات حرف خودتان اولویت بیشتری دارد یا محافظت از احساسات دیگران؟"
            ,"هنگام تصمیم گیری، بیشتر بر استدلال ها تکیه میکنید یا به حس شخیصی تان؟"
            ,"آیا هنگام قضاوت بیشتر به دنبال حقیقت هستید یا به تأثیر عاطفی تصمیم‌ها توجه می‌کنید؟"
            ,"آیا در تصمیم‌گیری، عدالت را بیشتر از همدردی ارزشمند می‌دانید؟"
            ,"آیا در محیط‌های رقابتی بهتر عمل می‌کنید یا در محیط‌هایی که همکاری و همدلی بیشتری وجود دارد؟"
            ,"آیا در زمان تصمیم‌گیری بیشتر به کارایی و سودمندی توجه می‌کنید یا به احساسات افراد؟"
            ,"آیا در هنگام تضاد حقایق و احساسات، معمولاً حرف دل خود را گوش می‌کنید؟"
            ,"آیا از حل مسائل پیچیده لذت می‌برید یا از برقراری ارتباط عمیق با افراد؟"
            ,"شما اغلب کارها را به صورت روشمند و بدون رد شدن از کنار هیچ مرحله‌ای انجام می‌دهید."
            ,"آیا در هنگام تصمیم‌گیری‌های مهم به فکت‌ها و اطلاعات علمی بیشتر اعتماد می‌کنید یا به احساسات و تجربیات شخصی؟"
            ,"آیا بیشتر به کیفیت و ارزش‌های فردی اهمیت می‌دهید یا به تأثیرگذاری و نتیجه عملی؟"
            ,"دلایل عاطفی به آسانی نظرتان را عوض نمی‌کنند."
            ,"در تصمیم گیری، کارایی را مد نظر قرار میدهید یا تاثیر جنبه های عاطفی آن بر روی دیگران را؟"
            ,"داستان‌ها و عواطف مردم از ارقام و داده‌ها برایتان مهم‌تر هستند."
            ,"آیا از اینکه به دیگران کمک کنید لذت می‌برید یا به فکر رسیدن به اهداف خود هستید؟"
            ,"آیا ترجیح می‌دهید برنامه‌ای دقیق داشته باشید یا به جریان امور سپرده شود؟"
            ,"آیا بیشتر به دنبال ساختار و نظم هستید یا انعطاف‌پذیری و آزادی؟"
            ,"شما دوست دارید از ابزارهای سازماندهی مثل برنامه‌های زمانی و لیست‌ها استفاده کنید."
            ,"شما دوست دارید همیشه یک فهرست از کارهای هر روز داشته باشید."
            ,"آیا حفظ ثبات در دنبال کردن یک برنامه کاری یا مطالعاتی برای شما چالش برانگیز است؟"
            ,"آیا تمایل دارید همیشه به برنامه‌ریزی‌های خود پایبند باشید یا به تغییرات و فرصت‌های جدید پاسخ دهید؟"
            ,"شما اغلب کارها را در آخرین لحظه ممکن انجام می‌دهید."
            ,"شما ترجیح می‌دهید قبل از این که به خودتان اجازه استراحت بدهید اول کارهای خود را انجام دهید."
            ,"آیا در محیط‌های ساختاریافته بهتر عمل می‌کنید یا در محیط‌های غیر رسمی و آزاد؟"
            ,"شما وظایف را به طور موثر اولویت‌بندی و برنامه‌ریزی می‌کنید و اغلب آنها را قبل از موعد مقرر به پایان می‌رسانید."
            ,"برنامه ریزی کردن را بیشتر دوست میدارید یا بداهه پردازی را؟"
            ,"آیا برای حل مشکلات ترجیح می‌دهید به سرعت به یک راه‌حل عملی برسید یا به بررسی ابعاد مختلف مشکل بپردازید؟"
            ,"آیا به راحتی می‌توانید با تغییرات جدید سازگار شوید یا ترجیح می‌دهید در چارچوب‌های شناخته شده باقی بمانید؟"
            ,"اغلب برای روز خود برنامه میریزید یا با جریان روز پیش می روید؟"
            ,"آیا در پروژه‌های گروهی به نقش‌های فردی و مسئولیت‌های مشخص اهمیت می‌دهید یا به همکاری آزاد و انعطاف‌پذیر؟"
            ,"سبک کاری فردی شما بیشتر به کدام مورد نزدیک تر است؟"
            ,"فضاهای زندگی و کاری شما تمیز و مرتب هستند."
]
