list_q_20 = [
            "Do you enjoy social gatherings?"
            ,"Do you find it easy to start conversations with strangers?"
            ,"Do you recharge by spending time with others or by reflecting alone?"
            ,"Do you find socializing energizing or exhausting?"
            ,"Do you enjoy being in a crowd or do you find it draining?"
            ,"Do you prefer to work on detailed tasks or big-picture ideas?"
            ,"Do you focus more on the present or the future?"
            ,"Do you rely more on facts or intuition when making decisions?"
            ,"When solving a problem, do you rely more on facts or creativity?"
            ,"Do you prefer practical or imaginative solutions?"
            ,"When you see a problem, do you want to solve it immediately or understand how it makes others feel?"
            ,"Do you approach difficult conversations by stating the facts or sharing your feelings?"
            ,"Do you make decisions based on logic or emotions?"
            ,"Do you prioritize fairness or empathy in decision-making?"
            ,"Do you value competence or compassion more?"
            ,"Do you prefer to stick to plans or be spontaneous?"
            ,"Do you prefer to have a structured routine or flexibility?"
            ,"Do you like to finish projects or start new ones?"
            ,"Do you prefer having clear goals or exploring possibilities?"
            ,"Do you like to plan in advance or improvise?"

]
list_qp_20 = [
            "آیا از جمع‌های اجتماعی لذت می‌برید؟"
            ,"آیا شروع مکالمه با افراد ناآشنا برایتان آسان است؟"
            ,"آیا با گذراندن وقت با دیگران یا تفکر تنها بیشتر شارژ می‌شوید؟"
            ,"آیا فکر می‌کنید که معاشرت با دیگران برایتان انرژی‌زا است یا خسته‌کننده؟"
            ,"آیا از بودن در جمع لذت می‌برید یا این وضعیت شما را خسته می‌کند؟"
            ,"آیا ترجیح می‌دهید روی کارهای دقیق یا ایده‌های کلی کار کنید؟"
            ,"آیا بیشتر بر روی حال حاضر تمرکز می‌کنید یا آینده؟"
            ,"آیا هنگام تصمیم‌گیری بیشتر به حقایق یا به شهود تکیه می‌کنید؟"
            ,"هنگام حل مشکل، بیشتر به حقایق یا خلاقیت تکیه می‌کنید؟"
            ,"آیا ترجیح می‌دهید راه‌حل‌های عملی یا تخیلی داشته باشید؟"
            ,"آیا تصمیمات خود را بر اساس منطق یا احساسات می‌گیرید؟"
            ,"آیا در تصمیم‌گیری، عدالت را بیشتر از همدردی ارزشمند می‌دانید؟"
            ,"آیا در تعاملات خود بیشتر به شایستگی یا دلسوزی اهمیت می‌دهید؟"
            ,"آیا هنگام بروز مشکل در ابتدا به دنبال راه‌حل هستید یا به نظرات و حرف دیگران توجه می‌کنید؟"
            ,"آیا هنگام قضاوت بیشتر به دنبال حقیقت هستید یا به تأثیر عاطفی تصمیم‌ها توجه می‌کنید؟"
            ,"آیا ترجیح می‌دهید به برنامه‌های از پیش تعیین‌شده پایبند باشید یا به صورت خودجوش عمل کنید؟"
            ,"آیا ترجیح می‌دهید یک روال منظم داشته باشید یا انعطاف‌پذیری را بیشتر بپسندید؟"
            ,"آیا ترجیح می‌دهید پروژه‌ها را به پایان برسانید یا پروژه‌های جدید را آغاز کنید؟"
            ,"آیا ترجیح می‌دهید اهداف مشخص داشته باشید یا به کشف امکانات بپردازید؟"
            ,"آیا بیشتر تمایل دارید به طور پیشرفته برنامه‌ریزی کنید یا به صورت بداهه عمل کنید؟"
]

list_a_20a = [
            "Yes"
            ,"Yes"
            ,"With others"
            ,"Energizing"
            ,"Enjoy"
            ,"Detailed tasks"
            ,"Present"
            ,"Facts"
            ,"Facts"
            ,"Practical"
            ,"Solve it immediately"
            ,"Stating facts"
            ,"Logic"
            ,"Fairness"
            ,"Competence"
            ,"Stick to plans"
            ,"Structured routine"
            ,"Finish projects"
            ,"Clear goals"
            ,"Plan in advance"
]
list_a_20b = [
            "No"
            ,"No"
            ,"Alone"
            ,"Exhausting"
            ,"Find it draining"
            ,"Big-picture ideas"
            ,"Future"
            ,"Intuition"
            ,"Creativity"
            ,"Imaginative"
            ,"Understand emotions"
            ,"Sharing"
            ,"Emotions"
            ,"Empathy"
            ,"Compassion"
            ,"Be spontaneous"
            ,"Flexibility"
            ,"Start new ones"
            ,"Exploring possibilities"
            ,"Improvise"
]

list_ap_20a = [
            "بله"
            ,"بله"
            ,"با دیگران"
            ,"انرژی‌زا"
            ,"لذت می‌برید"
            ,"کارهای دقیق"
            ,"حال حاضر"
            ,"حقایق"
            ,"حقایق"
            ,"عملی"
            ,"منطق"
            ,"بله"
            ,"شایستگی"
            ,"یافتن راه‌حل"
            ,"دنبال حقیقت"
            ,"پایبند به برنامه‌ها"
            ,"روال منظم"
            ,"به پایان برسانید"
            ,"اهداف مشخص"
            ,"برنامه‌ریزی پیشرفته"
]
list_ap_20b = [
            "خیر"
            ,"خیر"
            ,"تنها"
            ,"خسته‌کننده"
            ,"خسته می‌کند"
            ,"ایده‌های کلی"
            ,"آینده"
            ,"شهود"
            ,"خلاقیت"
            ,"تخیلی"
            ,"احساسات"
            ,"خیر"
            ,"دلسوزی"
            ,"نظرات و حرف دیگران"
            ,"توجه به تأثیر عاطفی"
            ,"عمل خودجوش"
            ,"انعطاف‌پذیری"
            ,"پروژه‌های جدید"
            ,"کشف امکانات"
            ,"عمل بداهه"
]